//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FCU.rc
//
#define IDD_FIRST                       100
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_CMP_DIR                     131
#define IDR_DIFF_DIR                    132
#define IDR_DIFF_FIL                    133
#define IDD_OPTIONS                     137
#define IDD_FILCMP_OPTIONS              137
#define IDD_FILDIFFVIEW                 138
#define IDR_DIFFEDIT_POPUP              143
#define IDR_DIRDIFF_POPUP               144
#define IDD_SAVE_COMP                   148
#define IDD_COLORS                      150
#define IDD_UNINSTALL                   151
#define IDB_Question                    152
#define IDD_USAGE                       153
#define IDD_COMPARE                     154
#define IDD_COPY_FILES                  157
#define IDD_SELECT_FILES                158
#define IDD_PASSWD                      161
#define IDD_EDITOR_OPTIONS              163
#define IDD_CMDLINE_OPTIONS             164
#define IDD_DIRCMP_OPTIONS              165
#define IDB_INS_MASK                    165
#define IDR_DIFF_EDIT                   166
#define IDD_FILDIFF_PRINT_OPTIONS       166
#define IDD_DIFFDIR_PRINT_OPTIONS       167
#define IDR_ACCELERATOR1                167
#define IDR_rtfUsage                    169
#define IDD_LAST                        300
#define IDS_MEMORY_ALLOC_FAIL           401
#define IDS_OUT_OF_MEMORY               402
#define IDS_PAGE_STR                    403
#define IDS_LIST_ALLOC_NEGATIVE         404
#define IDC_stLeftFile                  1000
#define IDC_VSIZE                       1001
#define IDC_stRightFile                 1001
#define IDC_HSIZE                       1002
#define IDC_CB_MASK                     1002
#define IDC_DIFF_LIST                   1003
#define IDC_BT_DIR1                     1004
#define IDC_BT_DIR2                     1006
#define IDC_CB_DIR1                     1007
#define IDC_CB_DIR2                     1008
#define IDC_CB_FILE_MASK                1009
#define IDC_CB_DIFF                     1010
#define IDC_CB_EXCLUDE_MASK             1011
#define IDC_CB_IDENTICAL                1012
#define IDC_ED_LEFT                     1013
#define IDC_CB_LEFT                     1014
#define IDC_ED_RIGHT                    1015
#define IDC_CB_RIGHT                    1016
#define IDC_ED_FOLDED                   1017
#define IDC_CB_DATE                     1018
#define IDC_CB_SIZE                     1019
#define IDC_CB_LEFT_WND                 1020
#define IDC_CB_TIME                     1021
#define IDC_RIGHT_WND                   1022
#define IDC_CB_SECONDS                  1023
#define IDC_CB_COMPOSED_WND             1024
#define IDC_CB_COMMENT                  1025
#define IDC_CB_SYNCSCROLLING            1026
#define IDC_CB_FIleNotifications        1027
#define IDC_CB_ShowNotifyDialog         1028
#define IDC_CK_IGN_EOL                  1029
#define IDC_CK_IGN_CASE                 1030
#define IDC_BN_COLOR_LEFT               1031
#define IDC_BN_COLOR_RIGHT              1032
#define IDC_BN_COLOR_FOLDED             1033
#define IDC_CK_FILECMP_DLG              1034
#define IDC_CK_DIRCMP_DLG               1035
#define IDC_TAB_WIDTH                   1036
#define IDC_BTN_FONT_CHANGE             1037
#define IDC_EB_FONT                     1038
#define IDC_NOTFOLDED                   1039
#define IDC_btnLeftColor                1039
#define IDC_rdFromLeftDir               1040
#define IDC_rdFromRightDir              1041
#define IDC_rdToLeftDir                 1042
#define IDC_rdToRightDir                1043
#define IDC_rdToSelectedDir             1044
#define IDC_btToSelectedDir             1045
#define IDC_ckLeftRightOnly             1046
#define IDC_ckPreserveSubdir            1047
#define IDC_ckIndentical                1048
#define IDC_cbOlder                     1049
#define IDC_ckMarkedFiles               1050
#define IDC_ckNewer                     1051
#define IDC_ckLeftOnly                  1052
#define IDC_ckRightOnly                 1053
#define IDC_ckIdentical                 1054
#define IDC_ckDifferent                 1055
#define IDC_cbFileMask                  1056
#define IDC_ckFiles                     1057
#define IDC_stToDir                     1058
#define IDC_cbToSelectedDir             1059
#define IDC_stFromDir                   1060
#define IDC_CHECK1                      1061
#define IDC_ckShowLineNo                1062
#define IDC_btnRightColor               1063
#define IDC_ckShowFileNames             1064
#define IDC_ebDescription               1065
#define IDC_btnShowFileList             1066
#define IDC_lstFiles                    1067
#define IDC_RD_CMP_SIZE_TIME            1068
#define IDC_RD_CMP_SIZE_CONTENTS        1069
#define IDC_ckOneInstance               1070
#define IDC_rdWrap                      1071
#define IDC_rdMsgBox                    1072
#define IDC_ebPasswd                    1073
#define IDC_ebUserName                  1073
#define IDC_rdInsLeftIdentSect          1074
#define IDC_ebKey                       1074
#define IDC_rdInsRightIdentSect         1075
#define IDC_btnMailTo                   1076
#define IDC_stEvalVersion               1077
#define IDC_btnRegister                 1078
#define IDC_stLine1                     1079
#define IDC_stLine2                     1080
#define IDC_stLine3                     1081
#define IDC_stPasswd                    1082
#define IDC_stThanks                    1083
#define IDC_stError                     1084
#define IDC_stUserName                  1084
#define IDC_btnWWW                      1085
#define IDC_CK_SUBDIR1                  1086
#define IDC_stKey                       1086
#define IDC_CK_IGN_BLANKS1              1087
#define IDC_ckFoldLines                 1088
#define IDC_stNotFoldedLines            1089
#define IDC_ckKeepTabs                  1090
#define IDC_ckShowTabs                  1091
#define IDC_ebLeftColor                 1092
#define IDC_ckPrintWithColors           1093
#define IDC_ebRightColor                1094
#define IDC_reUsage                     1128
#define IDD_CMP_FIL                     1149
#define IDC_CK_SUBDIR                   1500
#define IDC_ED_FRIGHT                   1501
#define IDC_ED_FMERGE                   1502
#define IDC_ED_FLEFT                    1503
#define IDC_R_RIGHT                     1504
#define IDC_R_LEFT                      1505
#define IDC_R_MERGE                     1506
#define IDC_B_SEL                       1507
#define IDC_CB_DIR                      1508
#define IDC_ED_COMPFILENAME             1509
#define IDC_B_SAVE_AS                   1510
#define IDC_R_SAVE_AS                   1511
#define IDC_GR_DIR                      1512
#define IDC_CK_IGN_BLANKS               1513
#define IDC_CB_FIL1                     1514
#define IDC_BT_FIL1                     1515
#define IDC_CB_FIL2                     1516
#define IDC_BT_FIL2                     1517
#define IDS_small                       2000
#define IDS_beautiful                   2001
#define IDS_PassedEndOfFile             2002
#define IDS_PassedBeginningOfFile       2003
#define IDS_ThereAreNoDifferencies      2004
#define IDS_NoMoreDifferencies          2005
#define IDS_TheFirstDifferenceReached   2006
#define IDS_AllFiles                    2007
#define IDS_LeftDifferentSection        2008
#define IDS_RightDifferentSection       2009
#define IDS_FoldedLineMarker            2010
#define IDS_ComparingDirectories        2011
#define IDS_File                        2012
#define IDS_View                        2013
#define IDS_Tools                       2014
#define IDS_Windows                     2015
#define IDS_Edit                        2016
#define IDS_left                        2017
#define IDS_right                       2018
#define IDS_XmlFiles                    2019
#define IDS_LeftOnly                    2020
#define IDS_RightOnly                   2021
#define IDS_MovedLeft                   2022
#define IDS_MovedRight                  2023
#define IDS_Identical                   2024
#define IDS_Properties                  2025
#define IDS_ComposedFileWasChanged      2801
#define IDS_FileReadonly                2802
#define IDS_UnknownErrorWhileReadingFile 2803
#define IDS_ErrorReadingLeftFile        2804
#define IDS_ErrorReadingRightFile       2805
#define IDS_ComparingFiles              2806
#define IDS_FileCmpBreakReceived        2807
#define IDS_YouWantToCreateDir          2808
#define IDS_Diffxx                      2809
#define IDS_NoFilenameSpecified         2810
#define IDS_SelectDirectory             2811
#define IDS_ComposedFileWasChanged2     2812
#define IDS_FileReadonly2               2813
#define IDS_UnknownErrorWhileReadingFile2 2814
#define IDS_ErrorReadingLeftFile2       2815
#define IDS_ErrorReadingRightFile2      2816
#define IDS_ComparingFiles2             2817
#define IDS_FileCmpBreakReceived2       2818
#define IDS_YouWantToCreateDir2         2819
#define IDS_Diffxx2                     2820
#define IDS_NoFilenameSpecified2        2821
#define IDS_SelectDirectory2            2822
#define ID_EDIT_DOWN                    24600
#define ID_EDIT_UP                      24601
#define ID_EDIT_LEFT                    24602
#define ID_EDIT_RIGHT                   24603
#define ID_EDIT_PGUP                    24604
#define ID_EDIT_PGDN                    24605
#define ID_EDIT_HOME                    24606
#define ID_EDIT_END                     24607
#define ID_EDIT_TOPFILE                 24608
#define ID_EDIT_BOTTOMFILE              24609
#define ID_EDIT_WORDLEFT                24610
#define ID_EDIT_WORDRIGHT               24611
#define ID_EDIT_SELECT_UP               24613
#define ID_EDIT_SELECT_LEFT             24614
#define ID_EDIT_SELECT_DOWN             24615
#define ID_EDIT_SELECT_END              24616
#define ID_EDIT_SELECT_HOME             24617
#define ID_EDIT_SELECT_PGDN             24618
#define ID_EDIT_SELECT_WORDLEFT         24619
#define ID_EDIT_SELECT_PGUP             24620
#define ID_EDIT_SELECT_RIGHT            24621
#define ID_EDIT_SELECT_WORDRIGHT        24622
#define ID_EDIT_BACKSPACE               24623
#define ID_EDIT_TAB                     24624
#define ID_EDIT_BACKTAB                 24625
#define ID_EDIT_FINDNEXT                24626
#define ID_BOOKMARKSET                  24627
#define ID_BOOKMARKNEXT                 24628
#define ID_EDIT_SELECT_BOTTOMFILE       24632
#define ID_EDIT_SELECT_TOPFILE          24633
#define ID_CMP_DIR                      32771
#define ID_CMP_FILE                     32772
#define ID_MRG_DIR                      32773
#define IDS_MGR_DIR                     32773
#define IDS_MGR_FILES                   32774
#define ID_VIEW_OPTIONS                 32776
#define ID_WINDOWS_LEFTFILE             32782
#define ID_WINDOWS_RIGHTFILE            32783
#define ID_WINDOWS_COMPFILE             32784
#define ID_VIEW_NEXTDIFF                32785
#define ID_VIEW_PREVDIFF                32786
#define ID_EDIT_INSERTRIGHT             32787
#define ID_EDIT_INSERTLEFT              32788
#define ID_VIEW_MOVEDDIFF               32789
#define ID_VIEW_PREVIOUSDIFF            32797
#define ID_WINDOWS_NEXT                 32805
#define ID_FILE_SAVECOMPOSED            32807
#define ID_EDIT_CMDMODE                 32808
#define ID_EDIT_INSERTBOTH              32811
#define ID_EDIT_DELETEDIFF              32812
#define ID_EDIT_RESTORELEFT             32813
#define ID_EDIT_RESTORERIGHT            32814
#define ID_INDICATOR_LINE               32815
#define ID_INDICATOR_DIFF               32816
#define ID_STATUSTEXT                   32817
#define ID_BREAK                        32824
#define ID_FILE_SAVE_DIFF_LIST          32830
#define ID_TOOLS_CUSTOMIZE_TOOLBAR      32838
#define ID_TOOLS_CUSTOMIZE_KEYBOARD     32839
#define ID_TOOLS_SELECTFILES            32840
#define ID_TOOLS_COPYFILES              32841
#define ID_TOOLS_CUSTOMIZE_USERTOOLS    32842
#define ID_HELP_CONTENTS                32844
#define ID_FOLD                         32845
#define ID_UNFOLD                       32846
#define ID_SMX_OPTIONS                  32847
#define ID_COPY_SELECTED_R              32848
#define ID_DELETE_SELECTED_R            32849
#define ID_OPEN_SELECTED_R              32850
#define ID_COPY_SELECTED_L              32852
#define ID_DELETE_SELECTED_L            32853
#define ID_OPEN_SELECTED_L              32854
#define ID_PROPERTIES_SELECTED_L        32855
#define ID_PROPERTIES_SELECTED_R        32856
#define ID_VIEW_REFRESH                 32857
#define ID_VIEW_NEXT_DIFF_FROM_CURSOR   32858
#define ID_FILE_XMLEXPORT               32859
#define ID_VIEW_LINEDIFF                32860
#define ID_EDIT_COMMENT                 32861
#define ID_VIEW_COMPAREAGAIN            32862
#define ID_PROPERTIES                   32863
#define ID_OPTIONS_SHOWLINENO           32864
#define ID_OPTIONS_FOLDLINES            32865
#define ID_OPTIONS_SYNCSCROLLING        32866
#define ID_USER_TOOLS_FIRST             32900
#define ID_USER_TOOLS_LAST              32950
#define IDS_STRING57606                 57606

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         32868
#define _APS_NEXT_CONTROL_VALUE         1129
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
